name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths: 
      - '.devcontainer/**'
  pull_request:
    branches: [ master ]
    paths: 
      - '.devcontainer/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag my-image-name:$(date +%s)
